HAI 1.2
  I HAS A NAME ITZ "JORDAN"
  VISIBLE "HAI WERLD"
  VISIBLE SMOOSH "I AM " NAME
  VISIBLE "WHATZ UR NAEM?"
  I HAS A URNAME
  GIMMEH URNAME
  VISIBLE SMOOSH "O HAI " URNAME
  VISIBLE "I'M LEAVE NOW KTHXBYE"
KTHXBYE