import random
print("Help me")
i=0
if(i==0):
    print("I need to stay strong")


class Helper:
    empowering_quotes = ["Self empowerment is seeking the solution rather than fixating on the problem." ,
                         "Stop giving people the power to steal your peace. It belongs to you and no one should be able to run away with it." ,
                         "You do have a story inside you; it lies articulate and waiting to be written behind your silence and your suffering. ",
                         "It is never too late to be who you might have been." ,
                         "Never be bullied into silence. Never allow yourself to be made a victim. Accept no one’s definition of your life, but define yourself." ,
                         "The power you have is to be the best version of yourself you can be, so you can create a better world." ,
                         "No one can make you feel inferior without your consent." ,
                         "Do we not realize that self respect comes with self reliance?" ,
                         "Never limit yourself to what you can't do, but to what you have the power to do with what you have." ,
                         "Reach high, for the stars lie hidden in your soul. Dream deep, for every dream precedes the goal." ,
                         "Integrating the mind is the essence of life. Decide you will always say and do only what you feel is right. Then, you will come to tremendous clarity and conviction in the inner and outer worlds." ,
                         "If you're not comfortable within yourself, you can't be comfortable with others." ,
                         "Your greatest risk is in thinking too small. Think big. Life is too short to think small." ,
                         "Never let success get to your head and never let failure get to your heart." ,
                         "Don’t ever compare yourself to others. You are not a copy, you are an original. Craft your own individuality and sense of style and just be yourself. Trying to be someone else will only frustrate you and make you unhappy and miserable." ,
                         "Courage is the first of human qualities because it is the quality which guarantees the others. ",
                         "You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously." ,
                         "Surround yourself with people who empower you to become better." ,
                         "Be who you are and say what you feel, because those who mind don’t matter, and those who matter don’t mind." ,
                         "The surest way to lose your self-worth is by trying to find it through the eyes of others." ,
                         "Every time you are tempted to react in the same old way, ask yourself if you want to be a prisoner of the past or a pioneer of the future." ,
                         "Trust yourself. There is no one else on earth that is better suited to determining your ideal and making it happen than you." ,
                         "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." ,
                         "Everything is happening all the time, but if you don't put yourself in the path of it, you miss it." ,
                         "He who is not everyday conquering some fear has not learned the secret of life." ,
                         "You are perfect as you are and there is always room for improvement. " ,
                         "Don't let the fear of losing be greater than the excitement of winning." ,
                         "Your self-worth is determined by you. You don't have to depend on someone telling you who you are." ,
                         "Stand up for what you believe in, even if it means standing alone. " ,
                         "You wanna fly, you got to give up the shit that weighs you down. ",
                         "Most of the shadows of life are caused by standing in our own sunshine.",
                         "What a man can be, he must be. This need we call self-actualization." ,
                         "The most common way people give up their power is by thinking they don’t have any." ,
                         "Everything you are against weakens you. Everything you are for empowers you." ,
                         "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new." ,
                         "Remember that just because you hit bottom doesn't mean you have to stay there." ,
                         "If you want light to come into your life, you need to stand where it is shining." ,
                         "Whenever a negative thought concerning your personal power comes to mind, deliberately voice a positive thought to cancel it out. " ,
                         "You've got to fight for what you believe in. If you don't try, you'll always wonder, and that's a horrible way to live." ,
                         "Feeling confident in your ability to protect yourself empowers you to live with less fear and more freedom." ,
                         "Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties.     " ,
                         "Following your passion is far more fulfilling than following the money." ,
                         "To be nobody but yourself in a world which is doing its best, night and day, to make you everybody else means to fight the hardest battle which any human being can fight; and never stop fighting." ,
                         "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve." ,
                         "Be yourself- not your idea of what you think somebody else’s idea of yourself should be. " ,
                         "You were born to be real not to be perfect." ,
                         "You must learn to be still in the midst of activity and to be vibrantly alive in repose." ,
                         "Great minds discuss ideas. Average minds discuss events. Small minds discuss people." ,
                         "Self-control is strength. Right thought is mastery. Calmness is power." ,
                         "Always be a first rate version of yourself and not a second rate version of someone else."
                         ]
